## Nornir Config File
---
core:
  num_workers: 100
inventory:
  plugin: "nornir.plugins.inventory.simple.SimpleInventory"
  options:
    host_file: 'C:\Users\Sadiq\PycharmProjects\Excel_Nornir\inventory\hosts.yaml'
    group_file: 'C:\Users\Sadiq\PycharmProjects\Excel_Nornir\inventory\groups.yaml'
    defaults_file: 'C:\Users\Sadiq\PycharmProjects\Excel_Nornir\inventory\defaults.yaml'

